### PR TITLE
Add a configure check to ensure we have std=c++11 support

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by peternewman** [comment]
@nomis52 this currently sets -std=c++11 in CXXFLAGS. Do we want that across everything, or just in some bits (in which case I can modify the code to not set CXXFLAGS)?

**Comment by nomis52** [comment]
I think it's safe to set -std=c++11 in CXXFLAGS.  Just try it and see.

**Comment by peternewman** [comment]
It's what it's currently doing and Travis is working. Do we bother testing the bits that are explicitly specifying c++11 in their Makefiles though?

**Comment by nomis52** [comment]
The bits that specify c++11 are the tests, so yes, running make check is the way to test this works. 
LGTM

**Comment by peternewman** [comment]
So do you want it removed from the mocks that explicitly specify it?

**Comment by nomis52** [comment]
Yeah, if we're setting it at the top level we don't need it in either of the Makefile.mk .

**Comment by peternewman** [comment]
Done.

**Comment by nomis52** [comment]
LGTM

**Pull request merged**
