### PR TITLE
Remove the old logging code.

### PR DESCRIPTION
**Pull request by nomis52**

### CODE REVIEW

**Comment by nomis52** [comment]
#72 should be reviewed first

**Comment by peternewman** [comment]
I'd rather wait for the merge to make this clearer.

**Comment by nomis52** [comment]
This is ready now

**Comment by peternewman** [comment]
LGTM, so how does logging work now?

**Comment by nomis52** [comment]
We have a CDC endpoint on the USB device, which is treated like a serial console. You just open the console with minicom / teraterm and you see the logs. No need for custom software

**Comment by peternewman** [comment]
Cool, I didn't realise that code was in already.

**Pull request merged**
