### PR TITLE
Updating project configuration

### PR DESCRIPTION
**Pull request by jmoyerman**

### CODE REVIEW

**Comment by nomis52** [comment]
LGTM

**Comment by peternewman** [comment]
Do we need to adapt the tarball checker?

**Comment by nomis52** [comment]
I don't plan on doing tarballs for this, since it's not something we plan to distribute to end users.

Unfortunately the build files here are netbeans XML, unless someone wants to write an XML parser .....

**Comment by nomis52** [comment]
LGTM, does this fix the build?

**Comment by peternewman** [comment]
I wasn't actually suggesting a tarball, just the same concept.

We could use an existing XML parser, or I suspect grep and sed would be enough to get the relevant filenames out and compare them to a tree walk.

**Pull request merged**
