### PR TITLE
Depend on the right version of OLA, closes #54

### LINKED ISSUE #54: Needs to depend on OLA>=0.9.6
Doesn't build with OLA 0.9.5 due to this https://github.com/OpenLightingProject/ola/pull/721#issuecomment-111821811

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by peternewman** [comment]
I'm guessing @nomis52 0.9.6-1alpha~precise isn't actually 0.9.6 inside given this is failing?

**Comment by peternewman** [comment]
Indeed:
configure:17640: checking for OLA
configure:17647: $PKG_CONFIG --exists --print-errors "libola >= 0.9.6"
Requested 'libola >= 0.9.6' but version of libola is 0.9.5
configure:17650: $? = 1
configure:17664: $PKG_CONFIG --exists --print-errors "libola >= 0.9.6"
Requested 'libola >= 0.9.6' but version of libola is 0.9.5
configure:17667: $? = 1
configure:17681: result: no
Requested 'libola >= 0.9.6' but version of libola is 0.9.5
configure:17697: error: Missing OLA, please install

**Comment by nomis52** [comment]
Yeah, the current .deb isn't 0.9.6.

Just leave this one for now, we can sort it out when 0.9.6 is officially out.

**Comment by peternewman** [comment]
Will re-open once 0.9.6 is out then.

**Pull request closed without merging**
