### PR TITLE
Add the initial hardware designs

### PR DESCRIPTION
**Pull request by nomis52**

### CODE REVIEW

**Comment by peternewman** [comment]
Is it worth having a folder per hardware design, to keep all it's bits together?

**Comment by nomis52** [comment]
Heh, yes, see my common on the other PR :)

**Comment by peternewman** [comment]
LED4 appears to be a power LED, but there is an LEDD still listed on pin 48 of the uC.

**Comment by peternewman** [comment]
I meant for the hardware layouts here, I guess it depends if you want it per board, including hardware, or per category and then board subfolders, either way this needs another folder.

**Comment by peternewman** [comment]
Can you fix the other comments please @nomis52 ?

**Comment by nomis52** [comment]
I can't. mrpacket will have to.

**Comment by nomis52** [comment]
@mrpackethead  so he sees the comment

**Pull request merged**
