### PR TITLE
Add the dot diagrams for the controller and responder.

### PR DESCRIPTION
**Pull request by nomis52**

### CODE REVIEW

**Comment by peternewman** [comment]
LGTM

You should update https://github.com/OpenLightingProject/ja-rule/blob/master/tests/config/ax_prog_doxygen.m4#L265 and Travis.

**Comment by peternewman** [comment]
And do the same as here:
https://github.com/OpenLightingProject/ola/pull/708

**Comment by peternewman** [comment]
We need to install graphviz via Travis too @nomis52 .

**Comment by nomis52** [comment]
We are:

 - if [ "$TASK" = "doxygen" ]; then sudo apt-get install -qq doxygen graphviz; fi

**Comment by peternewman** [comment]
Ah yes, I'd done it previously.

**Pull request merged**
